Olical/conjure

- deps.edn
Hi there, I came across your project and took it for a spin 🙌
This patch fixes the following warning (printed after exiting neovim):
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
We shouldn't need to specify a particular garbage collector implementation; let the JVM choose.
(You probably don't need `CMSClassUnloadingEnabled` either – it's ignored by the newer garbage collectors – but it doesn't do any harm.)
> Remove deprecated JVM option UseConcMarkSweepGC

- src/conjure/main.clj
Every time I quit neovim, I get a message on the terminal: `Conjure exited, restarting`, and the process never terminates, I need to kill it with `CTRL-C`, but it leaves a zombie java process on my system.
Debugging it, I found that conjure always exits with code 143. I think it means that the application was terminated due to a SIGTERM command.
I'm using openjdk version "1.8.0_202".
I took the `clean-up-and-exit` function from [nrepl](https://github.com/nrepl/nrepl):
https://github.com/nrepl/nrepl/blob/2b432c859c5a98b6e8c97338315bfaab2961641b/src/clojure/nrepl/cmdline.clj#L17-L23
> Stop JVM gracefully

- README.md
- autoload/conjure.vim
- lua/conjure.lua
- src/conjure/main.clj
- src/conjure/nvim/api.clj
- src/conjure/ui.clj
Related to #7, I wanted to see how looks like if Conjure's window log opens in an horizontal split, and wrote this code.
It adds 3 new variables, `g:conjure_log_direction`, `g:conjure_log_size_small` and `g:conjure_log_size_large` to define the direction and size of the Conjure log window.
Also modifies the size meaning. Before the size was the number of columns to use, now it is the percentage of the window to use. 
To me, makes more sense to make it a percentage, since sometimes I work on a small monitor (laptop) and other times on a bigger one.
> Make Conjure log window size and direction configurable

- README.md
- lua/conjure.lua
- plugin/conjure.vim
- src/conjure/action.clj
- src/conjure/nvim.clj
- src/conjure/ui.clj
So this has been mentioned a few times and here's the initial implementation! I also improved the quick doc virtual text and how it behaves. Now as you type (even in insert mode) you'll see quick doc, if you eval something (file, buffer, form _or_ root form) and it results in a single line output it'll appear as virtual text. The log buffer **will not open**.
You can still open it of course and it'll contain your history of evals, it'll also still open if there's more than one line in the output. I think this is a good middleground that will stop a bunch of window jank (where they pop in and out as you edit) just for one line results.
It takes up the same virtual text space as quick doc, so now you can always have the useful contextual information just at the end of your current line with …
> Virtual text eval

- .conjure.edn
- .lvimrc
- README.md
- deps.edn
- plugin/conjure.vim
- src/conjure/action.clj
- src/conjure/config.clj
- src/conjure/main.clj
- src/conjure/prepl.clj
- src/conjure/ui.clj
- src/conjure/util.clj
- test/conjure/config_test.clj
Closes #15, basically adds `.conjure.edn` config files and `ConjureUp` instead of `ConjureAdd|Remove|RemoveAll` commands. The new command will try to connect to everything in your config unless `:enabled?` is set to false. You can toggle `:enabled?` with the command with `ConjureUp +jvm -node` which you can bind as you wish.
Connections are now made as you open Neovim, no more opening then connecting! If you open Neovim without any configured connections it'll self prepl and warn you. The theory being if you have config you want to use that, if you don't have config you'll want _some_ sort of temporary eval to try something out.
If my theory is wrong, let me know! The readme has been updated so check that out for more documentation! Let me know how you get on!
> Declaritive prepl connections

- README.md
- plugin/conjure.vim
- src/conjure/ui.clj
I really like the way that errors are folded, and I deal with many large results, so I thought allowing folding of multiline results would be useful. Turns out it was quite easy to add.
It's fun to work on a Vim plugin written in Clojure.
> Optionally fold multiline results

- plugin/conjure.vim
This error message confused me initially. Now that I have context, I figured there was an opportunity to improve the error message a bit. Feedback welcome!
> Improve the wording of the message that prints when conjure exits unexpectedly

- doc/conjure.txt
* Fix incorrect "it's".
* Remove repetition of "configuration".
Feel free to drop the stylistic fix; it's just that when I re-read the paragraph, I noticed the multiple "configuration" and thought it could be a quick improvement.
> Main help file improvements

- deps.edn
Cleans up deprecated maven artifact warnings.
```
% clj
DEPRECATED: Libs must be qualified, change nrepl => nrepl/nrepl (/Users/penryu/.clojure/deps.edn)
Clojure 1.10.1
user=>
```
Ref: https://insideclojure.org/2020/07/28/clj-exec/
> qualify unqualified nrepl artifact in mvn specs

- doc/conjure-client-clojure-nrepl.txt
@Olical you mentioned this setting that allows evaluation of Clojure code from inside of a markdown file on my Reddit thread yesterday.  I thought it might be useful to add it to the docs.  You already cover this filetype_client stuff in [conjure.txt](https://github.com/Olical/conjure/blob/0e63269e176232cdd9f1c20d94dfd3b8ad5702a1/doc/conjure.txt#L196) but having it here might be a bit easier for people to find.   Feel free to  modify this or close it without merging if you disagree.
> Add docs for evaluating Clojure code in markdown

- fnl/conjure/eval.fnl
- lua/conjure/client/clojure/nrepl/action.lua
- lua/conjure/client/clojure/nrepl/server.lua
- lua/conjure/client/clojure/nrepl/state.lua
- lua/conjure/client/fennel/stdio.lua
- lua/conjure/client/janet/netrepl.lua
- lua/conjure/client/racket/stdio.lua
- lua/conjure/eval.lua
- lua/conjure/extract.lua
- lua/conjure/net.lua
- lua/conjure/remote/nrepl.lua
- lua/conjure/text.lua
I was trying to use `eval.marked-form` in a binding and couldn't hard code a mark name, so this happened.
I wasn't super sure on the names, but I didn't want to break backwards compatibility on `marked-form` so I left it the same.
One note, I tried running `make compile` as described in the contributing docs, but it changes a lot of things that don't seem to be related to my change. Did I mess something up? I will include them as a separate commit so it is easier to review, and if they do look ok then I can rebase them up before this gets merged.
> Refactor 'marked-form' into 'at-mark' and re-implement 'marked-form' using it.

- doc/conjure-client-fennel-stdio.txt
There is no easy solution to this until we can tell the fennel repl to
give us a client-friendly interface. So we document it in the hope that
the user can use the info to implement their own workaround. See #166
> Document bug in stdio fennel client with readline

- doc/conjure-client-fennel-stdio.txt
- fnl/conjure/client/fennel/stdio.fnl
- fnl/conjure/remote/stdio.fnl
- lua/conjure/client/fennel/stdio.lua
- lua/conjure/remote/stdio.lua
This fixes #166. The bug was caused by readline inserting control
characters into the fennel repl. By skipping the user readline config,
they are prevented from modifying the repl in arbitrary dangerous ways.
This is fine, because the readline editing facilities are completely
useless in the context of conjure, since we rely solely on neovim's
editing capabilities.
Note: The user is still able to configure the lua readline library
through their ~/.fennelrc file, for example, to persist their history.
> Prevent loading readline config on fennel stdio

- fnl/conjure/remote/socket.fnl
Sorry, I'd make a classic "forgot to push" mistake with #178.  Here is the missing de-duplication!
> remote.socket: Use strip-ansi-escape-sequences instead of gsub

- fnl/conjure/config.fnl
- fnl/conjure/eval.fnl
This implements highlights for evaluation as described in #113.  I did an almost direct conversion from @davidsierradz's Lua code to Fennel.
To configure (hopefully self-explanatory):
```
let g:conjure#highlight#enabled = 1
let g:conjure#highlight#timeout = 500
let g:conjure#highlight#group = "IncSearch"
```
These are the defaults, except for `enabled` which defaults to false.
Unfortunately, this requires a very recent NeoVim to work: more than 0.4.4, which is the latest release version at the time of writing.  I chose to make it silently fail on older versions.
I'm not sure if I called the Vim API functions in the correct idiomatic way.  I struggled to use `nvim` (i.e. `conjure.aniseed.nvim`) - it seemed to choke on the function name containing a dot (`highlight.range`).  Perhaps I …
> Implement highlight evaluation

- doc/conjure-client-clojure-nrepl.txt
- doc/conjure-client-fennel-aniseed.txt
- doc/conjure-client-fennel-stdio.txt
- doc/conjure-client-guile-socket.txt
- doc/conjure-client-hy-stdio.txt
- doc/conjure-client-janet-netrepl.txt
- doc/conjure-client-racket-stdio.txt
- doc/conjure-client-scheme-stdio.txt
- doc/conjure.txt
I find help tags for commands and configuration options very useful:
* easier to point somebody to a specific option like `:help g:conjure#log#wrap`
* allows jumping to documentation using `K` right from usage in init.vim
* allows jumping to mentions inside documentation using `K` or `Ctrl-]`
* makes options and commands more discoverable using `Helptags` from fzf-vim, vim-clap, or telescope
> Add help tags for commands and configuration options

- fnl/conjure/client/janet/netrepl.fnl
- fnl/conjure/remote/netrepl.fnl
- lua/conjure/client/janet/netrepl.lua
- lua/conjure/remote/netrepl.lua
This PR does two things:
Prior to the code being sent to the netrepl server for evaluation, the parser's row and column numbers are set to the value in `opts.range.start` (if either of these values are `nil`, `1` is used instead). This is done by sending a message prepended with `\xFF`. Messages of this type generate one response message: the result of evaluation.
Prior to the code being sent to the netrepl server for evaluation, the parser's source is updated to the value in `opts.file-path`. This is done by sending a message prepended with `\xFE`. Messages of this type generate two response messages: the result of the evaluation and the prompt.
As indicated above, some messages that are sent to the netrepl server generate one response message and some generate two response messages. …
> Send line/column and file path of evaluated code to Janet's netrepl server

- fnl/conjure/buffer.fnl
- lua/conjure/buffer.lua
Was throwing error with `:set debug=throw` activated.
Fixes #283
I thought i couldn't do it but actually i could :smile:
tests passes, maybe you want me to add another test here ?
Also if you have any suggestion on code quality or how i can do this patch in a better way i'd be happy to take any advice :)
> fix(buffer): pcall bufnr call because bufname can be invalid

- fnl/conjure/log.fnl
- lua/conjure/log.lua
Latest nvim changes requires arguments to win_is_valid to be a number.
It cannot depend on nil being treated as 0 anymore.
Fixes #293
> fix(log): ensure state.hud.id is truthy before close-hud

- fnl/conjure/client/clojure/nrepl/ui.fnl
- lua/conjure/client/clojure/nrepl/ui.lua
Following https://github.com/Olical/conjure/pull/274.
Currently when set `let g:conjure#client#clojure#nrepl#test#raw_out = v:true` and run the tests, all output will be prefixed with a `;` this makes syntax highlight not working.
This PR removes that `;`.
Before
After
> Raw printing in test mode

- fnl/conjure/client/clojure/nrepl/action.fnl
- fnl/conjure/fs.fnl
Fixes #317
Hi there Ollie! I'm trying to make my first Conjure contribution and I took a crack at this issue. This isn't ready for merging at all but I wanted to show you that I'm working on it. ~~I still need to get my nvim fennel setup functional and I haven't run any tests yet.~~
~~The change I made is basically so that `resolve-above` now takes a list of filenames and also has a 2-arity version that accepts a path. This path is expected to be a directory without a trailing slash which I believe is compatible with the current code. Then it goes up each level of the path hierarchy and searches for the nrepl files with the `findfiles` function already in place.~~
~~The surprisingly tricky bit is getting the parent directory from a path string since we can't use `vim.fn.findfile`'s upward …
> Check for each nREPL port file at each tree level (#317)

- fnl/conjure/client/guile/socket.fnl
- lua/conjure/client/guile/socket.lua
Using the Guile socket client, I noticed that my evaluations were not always getting evaluated in the correct context (module).  It was using the `BufEnter` autocmd, switching the module using the Guile REPL's `,m` command when the buffer changed.  It seems that this is not reliable, and sometimes it would fail to find the correct context and switch to the default module `(guile-user)` instead.  I think it might be somehow related to the presence of the log/HUD buffer, but I'm not sure at all.
This commit strips out all of the `BufEnter` stuff, and instead makes a separate `,m` command immediately before every evaluation.  The module name from `opts.context` in `eval-str`.
Whole file evaluations (`eval-file`) are run in the default module (`(guile-user)`), but if they begin with …
> Guile: Ensure that module is set before evaluation

- fnl/conjure/buffer.fnl
- lua/conjure/buffer.lua
> Explicitly load newly created log buffer

- fnl/conjure/mapping.fnl
- lua/conjure/mapping.lua
I noticed that with `buf2` on develop that missing descriptions show nothing
That's because you're using `:callback`. With 'legacy' `buf` you see the mapping, which is a bit friendlier:
So I figured I'd push some descriptions for the ones I didn't do before.
> Add descriptiors for other mappings

- fnl/conjure/client/python/stdio.fnl
I think I've solved the problem with embedded newline characters in Python source code. All of the examples in `dev/python/sandbox.py` evaluate correctly. I haven't tried it with other Python files yet. Just wanted to get something working for others to try on their code.
> fix for issue #437

- fnl/conjure/client/common-lisp/swank.fnl
- lua/conjure/client/common-lisp/swank.lua
Honestly, I'm not familiar with common lisp (only touching it lesser than a week), so will be good if someone with good common lisp knowledge approve it.
---
Original doc-str was constructing things like: `(describe #'list)`
<details> 
<summary>Eval result</summary>
```lisp
(describe #'list)
; #<FUNCTION LIST>
;   [compiled function]
; 
; 
; Lambda-list: (&REST ARGS)
; Declared type: (FUNCTION * (VALUES LIST &OPTIONAL))
; Derived type: (FUNCTION (&REST T) (VALUES LIST &OPTIONAL))
; Documentation:
;   Construct and return a list containing the objects ARGS.
; Known attributes: flushable, unsafely-flushable, movable
; Source file: SYS:SRC;CODE;LIST.LISP
```
</details>
and: `(describe #'defun)`
<details> 
<summary>Eval result</summary>
```lisp
(describe #'defun)
; COMMON-LISP:DEFUN is a …
```
> fix(swank): improve doc-str to work with any objects, not only functions

- fnl/conjure/client/python/stdio.fnl
- fnl/conjure/tree-sitter.fnl
- lua/conjure/client/python/stdio.lua
- lua/conjure/tree-sitter.lua
see https://github.com/neovim/neovim/pull/22761
vim.treesitter.query.get_node_text is deprecated, use new api instead
also resolve https://github.com/Olical/conjure/issues/477
> fix(deprecation): update treesitter function

- doc/conjure-client-scheme-stdio.txt
- fnl/conjure/client/scheme/stdio.fnl
- lua/conjure/client/guile/socket.lua
- lua/conjure/client/scheme/stdio.lua
Sorry, had to create another branch in my fork to isolate my other PR from this one.
I copied the interrupt function from the Racket client instead of the Python client because the Racket one uses the `send-signal` function from the base functionality in`remote/stdio.fnl`.
> Fix for issue #497 Scheme client

- fnl/conjure/client/hy/stdio.fnl
- fnl/conjure/client/julia/stdio.fnl
- fnl/conjure/client/python/stdio.fnl
- fnl/conjure/client/racket/stdio.fnl
- lua/conjure/client/hy/stdio.lua
- lua/conjure/client/julia/stdio.lua
- lua/conjure/client/python/stdio.lua
- lua/conjure/client/racket/stdio.lua
This is a minor nit but I noticed that the stdio-based clients use two equivalent implementations of the `interrupt` function. This PR makes the implementation the same for these clients:
- Hy
- Julia
- Python
- Racket
by using the:
- `send-signal` function defined in `remote/stdio.fnl`
- `vim.loop.constants.SIGINT` constant instead of the number 2
- `comment-prefix` of the client's language
Hopefully, this provides consistency and emphasizes the use of the base client functionality of `remote/stdio.fnl`.
I didn't include the Scheme client because there is https://github.com/Olical/conjure/pull/498 which adds the ability to interrupt the REPL.
> Use repl.send-signal to interrupt stdio REPLs

- README.adoc
- doc/conjure-client-janet-stdio.txt
- doc/conjure.txt
- fnl/conjure/client/janet/stdio.fnl
- lua/conjure/client/janet/stdio.lua
This is a basic stdio client for Janet based on some of the existing stdio clients.
There is already a nice netrepl-based client for Janet, though that requires one to install and setup a netrepl server for use.
A stdio-based client allows one to avoid the installation of both `jpm` and `spork` (possibly a speed bump for folks who are in the process of evaluating [1] Janet) but also might be nice for quick interactive sessions.  As with other stdio-based solutions though, functionality is reduced.  Perhaps a worthwhile trade-off for some situations.
This PR includes document updates and additions but the Wiki has not been updated yet.
---
[1] Pun intended :P
> Add a stdio based Janet client

- fnl/conjure/client/clojure/nrepl/debugger.fnl
- lua/conjure/client/clojure/nrepl/debugger.lua
When using the debugger, results from `:ConjureCljDebugInput eval` were not being displayed in the log buffer. It looks like these results are returned in the `:debug-value` field, so Conjure just needs to check if that field is available and print it if so.
For comparison, [here](https://github.com/clojure-emacs/cider-nrepl/blob/3824d72f9ba1a14f9ce9910500db0885f6b39c23/src/cider/nrepl/middleware/debug.clj#L390) is where the result is read in `cider-nrepl`, confirming that this is indeed the right field.
> Debugger: Show value of :debug-value if present

- fnl/conjure/client/guile/socket.fnl
- lua/conjure/client/guile/socket.lua
doc-str would silently fail and not display anything in nvim when used with Guile due to a missing check on the optional opts.on-result property. This PR fixes it
> Fix doc-str Guile

- fnl/conjure-spec/extract_spec.fnl
- lua/conjure-spec/extract_spec.lua
- scripts/setup-test-deps
This is my first try at converting an Aniseed test to *busted + luassert*.
I picked one that required a supporting test module that appears to be a one-off thing. I hope the integration of that module is OK. fennel code formatting might be a bit messed up by my Neovim set up. Advice and corrections are more than welcome.
> Convert extract tests, fix test setup

- fnl/conjure-spec/uuid_spec.fnl
- fnl/conjure/uuid.fnl
- lua/conjure-spec/uuid_spec.lua
- lua/conjure/uuid.lua
There are commented functions at the bottom of uuid.fnl and are useful when using Conjure for development.
To make things externally tesable, I exported the formerly private cats-and-dogs list to use in a busted test to verify that `v4` returns something in that list. I'm not sure if it's a good idea so if you think that we want to keep the cats-and-dogs private, I'm OK with that.
> Convert uuid.fnl and add test

- fnl/conjure-spec/stack_spec.fnl
- fnl/conjure-spec/text_spec.fnl
- fnl/conjure/stack.fnl
- fnl/conjure/text.fnl
- fnl/conjure/timer.fnl
- fnl/conjure/tree-sitter.fnl
- lua/conjure-spec/stack_spec.lua
- lua/conjure-spec/text_spec.lua
- lua/conjure/stack.lua
- lua/conjure/text.lua
- lua/conjure/timer.lua
- lua/conjure/tree-sitter.lua
More files converted along with corresponding tests.
> Convert tree-sitter.fnl, timer.fnl, text.fnl, stack.fnl, and tests

- fnl/conjure-spec/linked-list_spec.fnl
- fnl/conjure-spec/process_spec.fnl
- fnl/conjure-spec/promise_spec.fnl
- fnl/conjure-spec/school_spec.fnl
- fnl/conjure/eval.fnl
- fnl/conjure/hook.fnl
- fnl/conjure/inline.fnl
- fnl/conjure/linked-list.fnl
- fnl/conjure/log.fnl
- fnl/conjure/main.fnl
- fnl/conjure/process.fnl
- fnl/conjure/promise.fnl
- fnl/conjure/school.fnl
- lua/conjure-spec/linked-list_spec.lua
- lua/conjure-spec/process_spec.lua
- lua/conjure-spec/promise_spec.lua
- lua/conjure-spec/school_spec.lua
- lua/conjure/eval.lua
- lua/conjure/hook.lua
- lua/conjure/inline.lua
- lua/conjure/linked-list.lua
- lua/conjure/log.lua
- lua/conjure/main.lua
- lua/conjure/process.lua
- lua/conjure/promise.lua
- lua/conjure/school.lua
Converted more the straight-forward source files.
Created new busted test for legacy ones.
> More nfnl conversions

- fnl/conjure/client/sql/stdio.fnl
- fnl/conjure/remote/stdio-rt.fnl
- lua/conjure/client/sql/stdio.lua
- lua/conjure/remote/stdio-rt.lua
Tested  SQL client by evaluating SQL statements. The client uses a modified stdio module.
> Convert SQL client

- dev/python/sandbox.py
- dev/sql/pg-docker.sh
- fnl/conjure-spec/remote/stdio_spec.fnl
- fnl/conjure-spec/remote/transport/base64_spec.fnl
- fnl/conjure-spec/remote/transport/bencode_spec.fnl
- fnl/conjure/client/fennel/stdio.fnl
- fnl/conjure/client/hy/stdio.fnl
- fnl/conjure/client/janet/stdio.fnl
- fnl/conjure/client/julia/stdio.fnl
- fnl/conjure/client/python/stdio.fnl
- fnl/conjure/client/scheme/stdio.fnl
- fnl/conjure/client/snd-s7/stdio.fnl
- fnl/conjure/remote/stdio-rt.fnl
- fnl/conjure/remote/stdio.fnl
- fnl/conjure/remote/transport/base64.fnl
- fnl/conjure/remote/transport/bencode/init.fnl
- lua/conjure-spec/remote/stdio_spec.lua
- lua/conjure-spec/remote/transport/base64_spec.lua
- lua/conjure-spec/remote/transport/bencode_spec.lua
- lua/conjure/client/fennel/stdio.lua
- lua/conjure/client/hy/stdio.lua
- lua/conjure/client/janet/stdio.lua
- lua/conjure/client/julia/stdio.lua
- lua/conjure/client/python/stdio.lua
- lua/conjure/client/scheme/stdio.lua
- lua/conjure/client/snd-s7/stdio.lua
- lua/conjure/remote/stdio-rt.lua
- lua/conjure/remote/stdio.lua
- lua/conjure/remote/transport/base64.lua
- lua/conjure/remote/transport/bencode/init.lua
Converted clients:
- snd-s7
- Python (with small refinements)
- Scheme
- Hy (not tested)
- Julia (not tested)
- Janet stdio (not tested)
- Fennel stdio
Converted:
- remote/transport/base64
- remote/transport/bencode
- remote/stdio and associated test
Touch up:
- dev/python/sandbox.py
- remote/stdio-rt
> More conversions

- README.adoc
- fnl/conjure/fs.fnl
- lua/conjure/fs.lua
- plugin/conjure.lua
- plugin/conjure.vim
Hi,
I've seen that in the README was stated that Conjure works with neovim 0.7 or above. I've found in `fs.fnl` that `vim.fse.normalize` is been used, witch is a nvim 0.8+ feature so I've updated the minimum version required in the README and `plugin/conjure.vim`. With this version bump we unlock a lot of functionality that can replace some of the old batteries that were created.
I've also took the liberty to convert the `plugin/conjure.vim` to lua so we can use `vim.notify` instead of `echoerr`. `vim.notify` can integrate with other plugins and change the displaying of notifications (see example [noice.nvim](https://github.com/folke/noice.nvim))
> Refactor fs.fnl to use nvim 0.8 builtins

- fnl/conjure/client/fennel/stdio.fnl
using conjure with fennel file through an stdio REPL,  conjure  throws error after calling ,reload file command, error msg listed below.
E5108: Error executing lua: Vim:Error executing Lua callback: ...re/nvim/lazy/conjure/lua/conjure/client/fennel/stdio.lua:72: attempt to index global 'nvim' (a nil value)
stack traceback:
...re/nvim/lazy/conjure/lua/conjure/client/fennel/stdio.lua:72: in function <...re/nvim/lazy/conjure/lua/conjure/client/fennel/stdio.lua:71>
[C]: at 0x010249ae44
stack traceback:
[C]: at 0x010249ae44
> fix fennel client ,reload file error, nvim is nil

- fnl/conjure/tree-sitter.fnl
- lua/conjure/tree-sitter.lua
Hi,
this PR refactors treesitter.fnl to use neovim builtin api instead of using aniseed nvim module.
> Refactor treesitter.fnl to remove aniseed nvim module

- dev/rust/sandbox.rs
- fnl/conjure/client/rust/evcxr.fnl
- lua/conjure/client/rust/evcxr.lua
The addition of a `form-node?` function to the Rust client should make it more convenient to put your cursor on a line and evaluate statements or expressions.
The `dev/rust/sandbox.rs` has more comments to clarify how to evaluating things. I've included a link to the [Evcxr common usage information](https://github.com/evcxr/evcxr/blob/main/COMMON.md) document to help those not very familiar with Rust and `evcxr`.
> Improve selection of forms for Rust client

- fnl/conjure/client/clojure/nrepl/server.fnl
As discussed [here](https://clojurians.slack.com/archives/C17JYSA3H/p1744123473420459), we are adding nREPL client information to be able to provide metrics about the client of the nREPL.
Related to https://github.com/nrepl/nrepl/pull/370
> Add client-name to clone op

- fnl/conjure/client/hy/stdio.fnl
- fnl/conjure/client/julia/stdio.fnl
- fnl/conjure/client/python/stdio.fnl
- fnl/conjure/client/racket/stdio.fnl
- fnl/conjure/client/scheme/stdio.fnl
- fnl/conjure/client/snd-s7/stdio.fnl
- fnl/conjure/client/sql/stdio.fnl
- lua/conjure/client/hy/stdio.lua
- lua/conjure/client/julia/stdio.lua
- lua/conjure/client/python/stdio.lua
- lua/conjure/client/racket/stdio.lua
- lua/conjure/client/scheme/stdio.lua
- lua/conjure/client/snd-s7/stdio.lua
- lua/conjure/client/sql/stdio.lua
This is a minor fix to quiet the diagnostics from the `fennel-ls` language server when working with the `stdio`-based Conjure clients.
Just tidying this a bit so feel free to reject this PR.
> Fix unknown-module-field for vim.loop.constants.SIGINT

- doc/conjure-client-clojure-nrepl.txt
- fnl/conjure/client/clojure/nrepl/init.fnl
- fnl/conjure/client/clojure/nrepl/server.fnl
In some clojure codebases/test setups it is useful to setup custom clojure.test reporting methods, like:
```clojure
(defmethod clojure.test/report :fail [m]
;; whatever custom reporting code
)
```
But since https://github.com/Olical/conjure/pull/569, Conjure might override those, depending on if the nrepl connection is established before or after the codebase's custom clojure.test reporting methods are registered.
And you get conjure's version even in the presence of your own override:
```clojure
(get (methods t/report) :fail)
;; => #function[conjure.internal/eval127846/fn--127847]
```
Thus I figured it would be nice to be able to turn off conjure's registration of the `clojure.test/report` via a config flag.
This PR introduces a new config `:clojure :nrepl :test …
> Make it possible to turn off clojure.test failure pretty printing

- doc/conjure.txt
- fnl/conjure-spec/client/guile/fake-socket.fnl
- fnl/conjure-spec/client/guile/socket_spec.fnl
- fnl/conjure/client/guile/socket.fnl
- lua/conjure-spec/client/guile/fake-socket.lua
- lua/conjure-spec/client/guile/socket_spec.lua
- lua/conjure/client/guile/socket.lua
Preface:  I'm new to this code base's conventions and established practices as well as fennel, so I'm open to any comments or changes including the overall strategy (or opinion on overall usefulness).  These are additions which I've been using in my local fork as I've been playing with Guile and feel could be helpful to others.
The current behavior of the Guile REPL is to set the module in the REPL for a given context via `,m <module name>` before any `eval-str`.  However, this module space is completely uninitialized, even missing the basic language constructs like `define`.
Consider the following example Guile module file
```
(define-module (sample-module))
(module-name (current-module))
(define x 42)
x
```
Connecting to a fresh Guile REPL and evaluating the various expressions via …
> Initialize Guile modules in REPL for non-nil contexts

- fnl/conjure/client/python/stdio.fnl
- fnl/conjure/remote/stdio.fnl
- lua/conjure/client/python/stdio.lua
- lua/conjure/remote/stdio.lua
While trying to see how `nfnl`'s module hot reloading works, I:
- Changed the debug messages a bit for the Python client and the `remote.stdio` module that stdio-based clients use.
- Changed the `remote.stdio` module to use the nfnl hot reloading capability.
While editing `fnl/conjure/client/python/stdio.fnl`, I noticed that I needed to evalutate the file (`,ef`) before the new changes worked when editing `dev/python/sandbox.py` in another buffer.
`nfnl` hot reloading is awesome! It makes it easier to work on changes to Conjure clients. I can start one Neovim session and edit a client while using that client. Of course, in this case, I have my local Conjure repo being loaded as the Conjure plugin.
> Better debug msgs for Python client and use nfnl hot reload for remote.stdio module

- fnl/conjure-spec/client/guile/socket_spec.fnl
- fnl/conjure/client/guile/socket.fnl
- lua/conjure-spec/client/guile/socket_spec.lua
- lua/conjure/client/guile/socket.lua
If the Guile REPL has a pending operation the REPL-based completions cannot not process resulting in nvim hanging. 
This PR places a check around the REPL state's `:current` state which represents the running evaluation.
Evaluating the following as a form or buffer will place the REPL in a state where it cannot process completions for 5 seconds, after which it will resume.
```
(sleep 5)
```
This branch will continue to operation (sans completions) until the evaluation completes or the REPL is disconnected/reconnected.
> Prevent Guile REPL completions when eval is pending

- .nfnl.fnl
- fnl/conjure/client/fennel/def-str-util.fnl
- fnl/conjure/client/fennel/nfnl.fnl
- lua/conjure/client/fennel/def-str-util.lua
- lua/conjure/client/fennel/nfnl.lua
- res/queries/fennel/ext-def.scm
- res/queries/fennel/import-path.scm
- res/queries/fennel/local-def.scm
Although **jump to def** is already implemented by [fennel LSP solution](https://git.sr.ht/~xerool/fennel-ls), for people who want only to get a quick understanding on Fennel and do not bother to config LSP, it is still helpful for them to have an **out-of-box jump of def**. (Well, not 100% out-of-box, because it depends on treesitter.)
* Setup:  add the following code at the end of `fnl/conjure/client/fennel/nfnl.fnl `
```
(comment ;; testing code for def-str
(M.eval-file :dafa)
(def-str-util.search-and-jump :M.eval-file 99)
(def-str-util.search-targets def-str-util.def-query
(def-str-util.get-current-root)
0
99))
```
* Test
1. Evaluate the **last two expressions** to have an idea of how the APIs work. The first expression `(M.eval-file :dafa)` is not meant for evaluation.
2. Move cursor …
> cross file `jump to def` for Fennel (The nfnl client)
